# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_hstore.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty', models.SmallIntegerField(blank=True, null=True)),
                ('serialnumber', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True)),
                ('price_uah', models.IntegerField(blank=True, help_text='Стоимость в грн', null=True)),
                ('price_usd', models.IntegerField(blank=True, help_text='Ориентировачная стоимость в USD на момент покупки', null=True)),
                ('iscash', models.BooleanField(default=False, help_text='Оплачено наличными')),
                ('invoice', models.CharField(blank=True, help_text='Номер счета', max_length=16)),
                ('product_page', models.URLField(blank=True, help_text='url to pruduct page')),
                ('data', django_hstore.fields.DictionaryField(blank=True)),
            ],
            options={
                'verbose_name': 'Комплектующие',
                'verbose_name_plural': 'Комплектующие',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('kind', models.CharField(choices=[('ORG', 'Организация'), ('ROOM', 'Помещение'), ('BOX', 'Бокс'), ('TBL', 'Рабочее место'), ('PC', 'Компьютер')], max_length=4, null=True)),
                ('notice', models.TextField(blank=True, default='', max_length=300)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Свойство',
                'verbose_name_plural': 'Свойства',
            },
        ),
        migrations.CreateModel(
            name='SpareType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Тип железа',
                'verbose_name_plural': 'Тип железа',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('container_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Container')),
                ('os', models.CharField(blank=True, max_length=100)),
                ('ram', models.CharField(blank=True, max_length=20)),
                ('installation_date', models.CharField(blank=True, max_length=40, null=True)),
                ('speccy', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
            },
            bases=('inventory.container',),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='sparetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.SpareType'),
        ),
        migrations.AddField(
            model_name='container',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.Container'),
        ),
        migrations.AddField(
            model_name='component',
            name='container',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Container'),
        ),
        migrations.AddField(
            model_name='component',
            name='manufacture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Manufacture'),
        ),
        migrations.AddField(
            model_name='component',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Store'),
        ),
        migrations.AddField(
            model_name='component',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.SpareType'),
        ),
    ]
