# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_allcontainertree'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparetype',
            name='name_verbose',
            field=models.CharField(default='', max_length=32, verbose_name='Human-like название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sparetype',
            name='name',
            field=models.CharField(help_text='Это ключ, пишется английскими буквами, должен соответсвовать значению, возвращаемому парсером.', max_length=32),
        ),
    ]
