# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20160516_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='serialnumber',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Serial'),
        ),
    ]
