# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20160516_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
