# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20160516_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name': 'Комплектующие и устройства', 'verbose_name_plural': 'Комплектующие и устройства'},
        ),
        migrations.RenameField(
            model_name='component',
            old_name='unit_type',
            new_name='sparetype',
        ),
    ]
