# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-26 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20160519_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllContainerTree',
        ),
    ]
