# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-27 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_delete_allcontainertree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'ordering': ['name'], 'verbose_name': 'Компьютер', 'verbose_name_plural': 'Компьютеры'},
        ),
        migrations.AlterModelOptions(
            name='manufacture',
            options={'ordering': ['name'], 'verbose_name': 'Вендор', 'verbose_name_plural': 'Вендоры'},
        ),
        migrations.AlterModelOptions(
            name='sparetype',
            options={'ordering': ['name_verbose'], 'verbose_name': 'Тип железа', 'verbose_name_plural': 'Тип железа'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
    ]
