# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-03 14:49
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Фото компонента'),
        ),
    ]
