# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 20:05
from __future__ import unicode_literals

from django.db import migrations
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20161003_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=inventory.models.MyCloudinaryField(blank=True, max_length=255, null=True, verbose_name='Фото компонента'),
        ),
    ]
