# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-03 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20161005_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='price_usd',
        ),
        migrations.AlterField(
            model_name='component',
            name='invoice',
            field=models.CharField(blank=True, max_length=16, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='component',
            name='price_uah',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Стоимость в грн', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='product_page',
            field=models.URLField(blank=True, verbose_name='URL на страницу продукта'),
        ),
        migrations.AlterField(
            model_name='component',
            name='warranty',
            field=models.SmallIntegerField(blank=True, help_text='месяцев', null=True),
        ),
    ]
