# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-05 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20161103_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Это поле используется как help_text для поля price_uah на странице редактирования Компонента', max_digits=8, null=True),
        ),
    ]
