# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-05 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_component_price_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='manufacture',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='component',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
