# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-24 20:22
from __future__ import unicode_literals

from django.db import migrations


def create_init_history(apps, schema_editor):
    History = apps.get_model('inventory', 'History')
    Component = apps.get_model('inventory', 'Component')

    for component in Component.objects.all():
        h = History()
        h.container = component.container
        h.component = component
        h.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_history'),
    ]

    operations = [
        migrations.RunPython(create_init_history),
    ]
