# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-25 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20161224_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'История перемещений', 'verbose_name_plural': 'История перемещений'},
        ),
        migrations.AddField(
            model_name='component',
            name='parent',
            field=models.CharField(default='', help_text='Это вычисляемое поля для отображения в Grid, потому что его вычисление втемплейте очень тяжелое - для нескольких сотен компонентоввремя загрузки темплейта Grid возрастало с ~300ms до ~2100ms', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Container', verbose_name='Размещение'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
