# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-28 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20161225_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='parent',
            new_name='breadcrumbs',
        ),
        migrations.AddField(
            model_name='computer',
            name='breadcrumbs',
            field=models.CharField(default=0, help_text='Это вычисляемое поля для отображения в Grid', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='manufacturing_date',
            field=models.CharField(blank=True, help_text="Format: APR 2010 or Q2'2012 or 42/2014 (week/year). Please keep date format for future search ability!", max_length=20, null=True, verbose_name='Дата выпуска'),
        ),
    ]
