# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-09 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20161228_1820'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='computer',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='container',
            managers=[
            ],
        ),
    ]
