# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-11 20:46
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20170109_2307'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='computer',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='container',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
